inputSpec: uws/openapi.yml
generatorName: python-fastapi
outputDir: uws/generated/servers/python/fastapi
additionalProperties:
  fastapiImplementationPackage: uws_server_impl
  packageName: uws_server