inputSpec: uws/openapi.yml
generatorName: python-fastapi
outputDir: uws/generated/servers/python/fastapi
templateDir: templates/code_generation/python-fastapi
additionalProperties:
  fastapiImplementationPackage: impl
  packageName: uws_server
  rootPathPrefix: /uws
