# {{cookiecutter.protocol_full_title}} API Pattern

openapi: '3.0.3'

info:
  title: {{ cookiecutter.protocol_full_title }}
  version: '{{ cookiecutter.protocol_version }}'
  description: {{ cookiecutter.protocol_description }}
  contact:
    name: {{ cookiecutter.wg_name}}
    email: {{ cookiecutter.wg_email }}
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: /

tags:
  - name: {{ cookiecutter.protocol_name }}
    description: {{ cookiecutter.protocol_description}}

paths:
  /:
    get:
      operationId: getExample
      tags: [{{ cookiecutter.protocol_name }}]
      summary: Example of a GET operation
      responses:
        '200':
          description: 'Success'
          content:
            text/plain:
              schema:
                type: string
    post:
      operationId: postExample
      tags: [{{ cookiecutter.protocol_name }}]
      summary: Example of a POST operation
      requestBody:
        description: 'Example of a POST operation'
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExampleParameters'
      responses:
        '200':
          description: "Success"
          $ref: '#/components/responses/ExampleResponse'

components:
  responses:
    ExampleResponse:
      description: 'An example response - returns the provided parameters'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ExampleResponse'
  schemas:
    ExampleParameters:
      type: object
      title: exampleParameters
      description: 'An example of parameters that can be provided in a POST request'
      required:
        - example
      properties:
        example:
          type: string
          description: 'An example parameter'
          example: 'example'